src/Mobin.CoreProject.Admin/Controllers/ForestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mobin.CoreProject.Admin.Extensions;
using Mobin.CoreProject.Admin.Helper;
using Mobin.CoreProject.Core.DTOs.Forest;
using Mobin.CoreProject.Core.SearchCriteria.Forest;
using Mobin.CoreProject.Core.ServiceContracts;
using Mobin.CoreProject.Core.SSOT;
using Mobin.CoreProject.Core.ViewModels.Forest;
using Mobin.CoreProject.CrossCutting.Notification.Services;
using Mobin.CoreProject.CrossCutting.Security.ActionFilters;
using Mobin.CoreProject.CrossCutting.Security.Helper;

namespace Mobin.CoreProject.Admin.Controllers
{
    public class ForestController : Controller
    {
        private readonly IForestService _forestService;
        private readonly ISmsService _smsService;
        private readonly IEmailService _emailService;

        public ForestController(IForestService forestService, 
            ISmsService smsService, 
            IEmailService emailService)
        {
            _forestService = forestService;
            _smsService = smsService;
            _emailService = emailService;
        }

        public IActionResult Index(ForestGetDataSC criteria, int page = 1, int size = 10)
        {
            var model = _forestService.GetData(criteria, page, size);
            ViewBag.Q = criteria.Q;

            return View(model);
        }

        public IActionResult GetClaims()
        {
            var claims = User.Claims.Select(claim => new { claim.Type, claim.Value }).ToArray();
            return Json(claims);
        }

        public IActionResult GetEmployeeId()
        {
            var employeeId = User.GetClaim(Claims.EmployeeId.ToString());
            return Json(employeeId);
        }

        public async Task<IActionResult> SendSms()
        {
            var result = await _smsService.SendAsync(
                "09121063717",
                "http://localhost:5407/forest/sendsms",
                "50004001575",
                "Test");

            return Json(result);
        }

        public async Task<IActionResult> SendEmail()
        {
            var result = await _emailService.SendAsync(
                "test Client.SDK",
                "m.dashtinejad@mobinnet.net",
                "http://localhost:5407/forest/sendEmail");

            return Json(result);
        }


        #region Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ForestCreateVM vm)
        {
            var result = _forestService.Create(vm);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Edit), new { id = result.Data });
        }
        #endregion



        #region Edit
        public IActionResult Edit(int id)
        {
            var model = _forestService.Get<ForestEditDTO>(id);
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ForestEditVM vm, bool isAjax = false)
        {
            var result = _forestService.Update(id, vm);
            
            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Edit), new { id });
        }
        #endregion


        #region Delete
        public IActionResult Delete(int id, bool isAjax = false)
        {
            var result = _forestService.Delete(id);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion

        //[HasClaim(Claims.HotelId,"hotelId")]
        [HasClaim(Claims.HotelId)]
        public IActionResult HasClaim(int id /*int hotelId*/)
        {
            var list = User.Claims
                .Select(s => new
                {
                    s.Type,
                    s.Value
                })
                .ToList();
                

            return Json(list);

        }

        [HasPermission(Permissions.Dashboard)]
        public IActionResult HasPermission()
        {
            var list = User.Claims
                .Select(s => new
                {
                    s.Type,
                    s.Value
                })
                .ToList();
                

            return Json(list);
        }
    }


}

src/Mobin.CoreProject.Admin/Controllers/LoggingController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mobin.CoreProject.Admin.Controllers
{
    public class LoggingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Mobin.CoreProject.Admin/Controllers/RoleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mobin.CoreProject.Admin.Extensions;
using Mobin.CoreProject.Admin.Helper;
using Mobin.CoreProject.Core.Helpers;
using Mobin.CoreProject.Core.SSOT;
using Mobin.CoreProject.CrossCutting.Security.Helper;
using Mobin.CoreProject.CrossCutting.Security.Services;

namespace Mobin.CoreProject.Admin.Controllers
{
    // [HasPermission(Permissions.UserAndRoles)]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;

        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public IActionResult Index()
        {
            var model = _roleService.GetAll();
            return View(model);
        }

        #region CreateRole
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string name)
        {
            var result = await _roleService.CreateAsync(name);

            TempData.AddResult(result);


            return result.Succeed
                ? RedirectToAction(nameof(EditClaims), new { id = result.Data })
                : RedirectToAction(nameof(Create));
        }
        #endregion





        #region UpdateRoleTitle
        public async Task<IActionResult> EditName(int id)
        {
            var role = await _roleService.FindByIdAsync(id);
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditName(int id, string title, bool isAjax = false)
        {
            var result = await _roleService.UpdateAsync(id, title);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(EditName));
        }
        #endregion


        #region UpdateRoleClaims
        public async Task<IActionResult> EditClaims(int id)
        {
            var role = await _roleService.FindByIdAsync(id);
            var roleClaims = await _roleService.GetClaimsAsync(role);
            var roleClaimsStringArray = roleClaims.Select(c => c.Value).ToList();

            var allClaims = EnumHelper.EnumToList(typeof(Permissions));

            ViewBag.RoleClaimsStringArray = roleClaimsStringArray;
            ViewBag.AllClaims = allClaims;

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditClaims(int id, List<string> claims, bool isAjax = false)
        {
            var result = await _roleService.UpdatePermissions(id, claims);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(EditClaims), new { id });

        }
        #endregion


        #region DeleteRole
        public async Task<IActionResult> Delete(int id, bool isAjax = false)
        {
            var result = await _roleService.DeleteAsync(id);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion


    }
}

src/Mobin.CoreProject.Admin/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Alamut.Data.Structure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mobin.CoreProject.Admin.Extensions;
using Mobin.CoreProject.Core.Helpers;
using Mobin.CoreProject.Core.SSOT;
using Mobin.CoreProject.CrossCutting.Security.Models;
using Mobin.CoreProject.CrossCutting.Security.Services;
using Newtonsoft.Json;

namespace Mobin.CoreProject.Admin.Controllers
{

    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        public UserController(IUserService userService, IRoleService roleService)
        {
            _userService = userService;
            _roleService = roleService;
        }

        public IActionResult Index()
        {
            var model = _userService.GetAll();
            return View(model);
        }

        #region CreateUser
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string userName)
        {
            var result = await _userService.CreateDomainUserAsync(userName);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion


        #region EditUsername
        public async Task<IActionResult> EditUsername(int id)
        {
            var user = await _userService.FindByIdAsync(id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUsername(int id, string newUsername)
        {
            var result = await _userService.RenameUsername(id, newUsername);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }

        #endregion


        #region UpdateUserRoles
        public async Task<IActionResult> EditRoles(int id)
        {
            var user = await _userService.FindByIdAsync(id);
            var roles = _roleService.GetAll();
            var userRoles = await _userService.GetRolesAsync(user);

            ViewBag.UserRoles = userRoles;
            ViewBag.User = user;

            return View(roles);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRoles(int id, List<int> roleIds, bool isAjax)
        {
            var result = await _userService.UpdateRoles(id, roleIds);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(EditRoles), new { id });

        }
        #endregion

        #region Delete User
        public async Task<IActionResult> Delete(int id, bool isAjax = false)
        {
            var result = await _userService.DeleteAsync(id);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion


        #region UpdateClaims
        public async Task<IActionResult> EditClaims(int id)
        {
            var user = await _userService.FindByIdAsync(id);
            var userClaims = await _userService.GetClaimsAsync(id);
            var allClaims = EnumHelper.EnumToList(typeof(Claims));

            var model = new UserEditClaimsPM
            {
                User = user,
                UserClaims = userClaims,
                AllClaims = allClaims,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditClaims(int id, string claimType, string claimValue)
        {
            var result = await _userService.SetClaimAsync(id, claimType, claimValue);

            TempData.AddResult(result);
            return RedirectToAction(nameof(EditClaims), new { id });

        }

        public async Task<IActionResult> DeleteSingleClaim(int id, string claimType, string claimValue, bool isAjax = false)
        {
            var result = await _userService.RemoveClaimAsync(id, claimType, claimValue);

            if (isAjax) return Json(result);

            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region CreatePublicUser

        public IActionResult CreatePublicUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePublicUser(string userName, string password)
        {
            var callbackUrl = Url.Page(
                "/Account/ConfirmEmail",
                pageHandler: null,
                values: null,
                protocol: Request.Scheme);
            

            var result = await _userService.CreatePublicUserAsync(userName, password,
                userName, // optional
                callbackUrl); // optional

            TempData.AddResult(result);

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region EditPublicUsername
        public async Task<IActionResult> EditPublicUsername(int id)
        {
            var user = await _userService.FindByIdAsync(id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPublicUsername(int id, string newUsername, string newPassword)
        {
            var result = await _userService.RenameUsername(id, newUsername);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Index));
        }
        #endregion

    }


    public class UserEditClaimsPM
    {
        public AppUser User { get; set; }
        public IList<Claim> UserClaims { get; set; }
        public List<EnumHelper.EnumModel> AllClaims { get; set; }
    }
}

src/Mobin.CoreProject.Admin/Views/Shared/_BreadCrumb.cshtml
@using Mobin.CoreProject.Admin.Toolkit

@{ BreadCrumb breadCrumb = ViewBag.BreadCrumb; }


@if (breadCrumb != null)
{
    <div class="bg-body-light">
        <div class="content content-full" style="padding-top: 0.5rem; padding-bottom: 0.5rem;">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill font-size-h3 font-w400 mt-2 mb-0 mb-sm-2">@ViewData["Title"]</h1>

                @if (breadCrumb.Links != null)
                {
                    <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            @foreach (var item in breadCrumb.Links)
                            {
                                <li class="breadcrumb-item @(string.IsNullOrWhiteSpace(item.Link) ? " active " : "")">
                                    @if (string.IsNullOrWhiteSpace(item.Link))
                                    {
                                        <span>@item.Title</span>
                                    }
                                    else
                                    {
                                        <a href="@item.Link">@item.Title</a>
                                    }
                                </li>
                            }
                        </ol>
                    </nav>
                }
                

            </div>
        </div>
    </div>
}

src/Mobin.CoreProject.Admin/Views/Shared/_Sidebar.cshtml
<!-- Sidebar -->
<!--
    Sidebar Mini Mode - Display Helper classes

    Adding 'smini-hide' class to an element will make it invisible (opacity: 0) when the sidebar is in mini mode
    Adding 'smini-show' class to an element will make it visible (opacity: 1) when the sidebar is in mini mode
        If you would like to disable the transition animation, make sure to also add the 'no-transition' class to your element

    Adding 'smini-hidden' to an element will hide it when the sidebar is in mini mode
    Adding 'smini-visible' to an element will show it (display: inline-block) only when the sidebar is in mini mode
    Adding 'smini-visible-block' to an element will show it (display: block) only when the sidebar is in mini mode
-->
<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    <div class="bg-header-dark">
        <div class="content-header bg-white-10">
            <!-- Logo -->
            <a class="link-fx font-w600 font-size-lg text-white" href="/">
                <span class="smini-hidden">
                    <span class="text-white-75">Core</span><span class="text-white">Project</span>
                </span>
            </a>
            <!-- END Logo -->
            <!-- Options -->
            <div>
                <!-- END Toggle Sidebar Style -->
                <!-- Close Sidebar, Visible only on mobile screens -->
                <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                <a class="d-lg-none text-white ml-2" data-toggle="layout" data-action="sidebar_close" href="javascript:void(0)">
                    <i class="fa fa-times-circle"></i>
                </a>
                <!-- END Close Sidebar -->
            </div>
            <!-- END Options -->
        </div>
    </div>
    <!-- END Side Header -->
    <!-- Side Navigation -->
    <div class="content-side content-side-full">
        <ul class="nav-main">
            <li class="nav-main-item">
                <a class="nav-main-link" asp-controller="Home" asp-action="Index">
                    <i class="nav-main-link-icon si si-grid"></i>
                    <span class="nav-main-link-name">داشبورد</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link" asp-controller="Forest" asp-action="Index">
                    <i class="nav-main-link-icon si si-chemistry"></i>
                    <span class="nav-main-link-name">درخت</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link" asp-controller="User" asp-action="Index">
                    <i class="nav-main-link-icon si si-user"></i>
                    <span class="nav-main-link-name">مدیریت کاربران</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link" asp-controller="Role" asp-action="Index">
                    <i class="nav-main-link-icon si si-game-controller"></i>
                    <span class="nav-main-link-name">مدیریت نقش‌ها</span>
                </a>
            </li>
            <li class="nav-main-item">
                <a class="nav-main-link" asp-controller="Logging" asp-action="Index">
                    <i class="nav-main-link-icon si si-book-open"></i>
                    <span class="nav-main-link-name">Logging</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- END Side Navigation -->
</nav>
<!-- END Sidebar -->